# Generated by Django 5.2 on 2025-10-01 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unidad', models.CharField(default='', max_length=10)),
                ('tipo_metrica', models.CharField(choices=[('CANTIDAD', 'Cantidad'), ('MONTO', 'Monto'), ('PORCENTAJE', 'Porcentaje'), ('TIEMPO', 'Tiempo')], max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Métrica del Dashboard',
                'verbose_name_plural': 'Métricas del Dashboard',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_reporte', models.CharField(choices=[('RESUMEN', 'Resumen'), ('DETALLADO', 'Detallado'), ('ANALITICO', 'Analítico'), ('COMPARATIVO', 'Comparativo')], max_length=20)),
                ('campos_incluidos', models.JSONField(default=list, help_text='Lista de campos a incluir en el reporte')),
                ('filtros_default', models.JSONField(default=dict, help_text='Filtros por defecto para el reporte')),
                ('agrupacion', models.CharField(blank=True, help_text='Campo por el cual agrupar los datos', max_length=50)),
                ('ordenamiento', models.CharField(default='-fecha_ajuste', help_text='Campo para ordenar los resultados', max_length=50)),
                ('formato_default', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('es_publico', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros utilizados para generar el reporte')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/')),
                ('registros_procesados', models.PositiveIntegerField(default=0)),
                ('tiempo_ejecucion', models.DurationField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='analytics.reporttemplate')),
            ],
            options={
                'verbose_name': 'Ejecución de Reporte',
                'verbose_name_plural': 'Ejecuciones de Reportes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('recurso', models.CharField(max_length=100)),
                ('recurso_id', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='analytics_u_usuario_4bf921_idx'), models.Index(fields=['accion'], name='analytics_u_accion_54449c_idx'), models.Index(fields=['recurso'], name='analytics_u_recurso_689023_idx')],
            },
        ),
    ]
