# Generated by Django 5.2 on 2025-10-01 18:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('REVERSO', 'Reverso'), ('CORRECCION', 'Corrección')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ajuste',
                'verbose_name_plural': 'Tipos de Ajustes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AjusteFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ajuste', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_ajuste', models.DateTimeField()),
                ('fecha_valor', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('justificacion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=10)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_documento_origen', models.CharField(blank=True, max_length=50)),
                ('referencia_externa', models.CharField(blank=True, max_length=100)),
                ('centro_costo', models.CharField(blank=True, max_length=50)),
                ('usuario_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_procesados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_credito', to='adjustments.cuentacontable')),
                ('cuenta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_debito', to='adjustments.cuentacontable')),
                ('tipo_ajuste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adjustments.tipoajuste')),
            ],
            options={
                'verbose_name': 'Ajuste Financiero',
                'verbose_name_plural': 'Ajustes Financieros',
                'ordering': ['-fecha_ajuste', '-numero_ajuste'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='ajustes/archivos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('tamaño', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('tipo_contenido', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='adjustments.ajustefinanciero')),
                ('usuario_subida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('es_interno', models.BooleanField(default=False, help_text='Comentario visible solo para usuarios internos')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='adjustments.ajustefinanciero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Ajuste',
                'verbose_name_plural': 'Comentarios de Ajustes',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], max_length=10)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='adjustments.ajustefinanciero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Ajuste',
                'verbose_name_plural': 'Historiales de Ajustes',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='ajustefinanciero',
            index=models.Index(fields=['numero_ajuste'], name='adjustments_numero__9c0863_idx'),
        ),
        migrations.AddIndex(
            model_name='ajustefinanciero',
            index=models.Index(fields=['fecha_ajuste'], name='adjustments_fecha_a_e1d1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ajustefinanciero',
            index=models.Index(fields=['estado'], name='adjustments_estado_3dce34_idx'),
        ),
        migrations.AddIndex(
            model_name='ajustefinanciero',
            index=models.Index(fields=['tipo_ajuste'], name='adjustments_tipo_aj_b117d9_idx'),
        ),
        migrations.AddIndex(
            model_name='ajustefinanciero',
            index=models.Index(fields=['usuario_creador'], name='adjustments_usuario_9a0d43_idx'),
        ),
    ]
