# Generated by Django 5.2 on 2025-10-01 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjustments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuenta', models.CharField(max_length=50, verbose_name='ID de Cuenta')),
                ('id_acuerdo_servicio', models.CharField(max_length=50, verbose_name='ID de Acuerdo de Servicio')),
                ('id_cargo_facturable', models.CharField(max_length=50, verbose_name='ID de Cargo Facturable')),
                ('fecha_ajuste', models.DateField(verbose_name='Fecha de Ajuste')),
                ('asesor_que_ajusto', models.CharField(max_length=100, verbose_name='Asesor que Ajustó')),
                ('valor_ajustado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Ajustado')),
                ('obs_adicional', models.TextField(blank=True, verbose_name='Observaciones Adicionales')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ajuste',
                'verbose_name_plural': 'Registros de Ajustes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_cuenta'], name='adjustments_id_cuen_647a30_idx'), models.Index(fields=['fecha_ajuste'], name='adjustments_fecha_a_b2f3df_idx'), models.Index(fields=['asesor_que_ajusto'], name='adjustments_asesor__82eeca_idx'), models.Index(fields=['created_at'], name='adjustments_created_3f2327_idx')],
            },
        ),
    ]
