# Generated by Django 5.2 on 2025-10-02 14:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjustments', '0002_registroajuste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroajuste',
            options={'ordering': ['-created_at'], 'permissions': [('view_high_value_adjustments', 'Puede ver ajustes de alto valor'), ('approve_adjustments', 'Puede aprobar ajustes'), ('export_adjustments', 'Puede exportar ajustes')], 'verbose_name': 'Registro de Ajuste', 'verbose_name_plural': 'Registros de Ajustes'},
        ),
        migrations.RenameIndex(
            model_name='registroajuste',
            new_name='idx_cuenta',
            old_name='adjustments_id_cuen_647a30_idx',
        ),
        migrations.RenameIndex(
            model_name='registroajuste',
            new_name='idx_fecha_ajuste',
            old_name='adjustments_fecha_a_b2f3df_idx',
        ),
        migrations.RenameIndex(
            model_name='registroajuste',
            new_name='idx_asesor',
            old_name='adjustments_asesor__82eeca_idx',
        ),
        migrations.RenameIndex(
            model_name='registroajuste',
            new_name='idx_created_at',
            old_name='adjustments_created_3f2327_idx',
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='asesor_que_ajusto',
            field=models.CharField(db_index=True, help_text='Nombre completo del asesor responsable del ajuste', max_length=100, verbose_name='Asesor que Ajustó'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp automático de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='fecha_ajuste',
            field=models.DateField(db_index=True, help_text='Fecha en la que se realiza el ajuste (no puede ser futura)', verbose_name='Fecha de Ajuste'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='id_acuerdo_servicio',
            field=models.CharField(db_index=True, help_text='Identificador del acuerdo de servicio asociado', max_length=50, verbose_name='ID de Acuerdo de Servicio'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='id_cargo_facturable',
            field=models.CharField(help_text='Identificador del cargo facturable específico', max_length=50, verbose_name='ID de Cargo Facturable'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='id_cuenta',
            field=models.CharField(db_index=True, help_text='Identificador único de la cuenta contable', max_length=50, verbose_name='ID de Cuenta'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='justificacion',
            field=models.TextField(help_text='Justificación detallada para el ajuste (obligatorio)', max_length=2000, verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='obs_adicional',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre el ajuste (opcional)', max_length=1000, verbose_name='Observaciones Adicionales'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp automático de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='registroajuste',
            name='valor_ajustado',
            field=models.DecimalField(decimal_places=2, help_text='Monto del ajuste en pesos colombianos (debe ser negativo para deducciones)', max_digits=15, validators=[django.core.validators.MaxValueValidator(Decimal('-0.01'), message='El valor del ajuste debe ser negativo'), django.core.validators.MinValueValidator(Decimal('-999999999999.99'), message='El valor excede el límite mínimo permitido')], verbose_name='Valor Ajustado'),
        ),
        migrations.AddIndex(
            model_name='registroajuste',
            index=models.Index(fields=['valor_ajustado'], name='idx_valor'),
        ),
        migrations.AddIndex(
            model_name='registroajuste',
            index=models.Index(fields=['id_cuenta', 'fecha_ajuste'], name='idx_cuenta_fecha'),
        ),
    ]
