# Generated by Django 5.2 on 2025-10-02 14:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjustments', '0003_fix_negative_adjustment_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustefinanciero',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MaxValueValidator(Decimal('-0.01'), message='El valor del ajuste debe ser negativo'), django.core.validators.MinValueValidator(Decimal('-999999999999.99'), message='El valor excede el límite mínimo permitido')]),
        ),
    ]
