# Generated by Django 5.2 on 2025-10-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjustments', '0004_update_negative_values_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroajuste',
            name='obs_adicional',
        ),
    ]
