# Generated by Django 5.2 on 2025-10-01 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Sesión',
                'verbose_name_plural': 'Logs de Sesiones',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Máximo 15 dígitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('documento_identidad', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('tema_preferido', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10)),
                ('puede_aprobar_ajustes', models.BooleanField(default=False, help_text='Puede aprobar ajustes financieros')),
                ('puede_procesar_ajustes', models.BooleanField(default=False, help_text='Puede procesar ajustes aprobados')),
                ('limite_aprobacion', models.DecimalField(blank=True, decimal_places=2, help_text='Límite de monto para aprobación', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
